/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FancyDataTable: typeof import('./src/components/FancyDataTable.vue')['default']
    FormInput: typeof import('./src/components/FormInput.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ModernDialog: typeof import('./src/components/ModernDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerTest: typeof import('./src/components/ServerTest.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}
